(cl:in-package keyboard-msg)
(cl:export '(HEADER-VAL
          HEADER
          K_I-VAL
          K_I
          K_H-VAL
          K_H
          K_Y-VAL
          K_Y
          K_Z-VAL
          K_Z
          K_Q-VAL
          K_Q
          K_P-VAL
          K_P
          K_S-VAL
          K_S
          K_N-VAL
          K_N
          K_T-VAL
          K_T
          K_W-VAL
          K_W
          K_V-VAL
          K_V
          K_A-VAL
          K_A
          K_K-VAL
          K_K
          K_J-VAL
          K_J
          K_M-VAL
          K_M
          K_L-VAL
          K_L
          K_O-VAL
          K_O
          K_C-VAL
          K_C
          K_B-VAL
          K_B
          K_E-VAL
          K_E
          K_D-VAL
          K_D
          K_G-VAL
          K_G
          K_F-VAL
          K_F
          K_R-VAL
          K_R
          K_X-VAL
          K_X
          K_U-VAL
          K_U
))